--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Xenophilicy/Decorations
build-by-default: true
branches:
- master
projects:
  Decorations:
    lint:
      phpstan: false
    path: ""
    libs:
      - src: BreathTakinglyBinary/libDynamicForms/libDynamicForms
        version: ^1.1.2
...
